"""auth e estrutura

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 10:14:11.465990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_areas')),
    sa.UniqueConstraint('nome', name=op.f('uq_areas_nome'))
    )
    op.create_table('perfis',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_perfis')),
    sa.UniqueConstraint('nome', name=op.f('uq_perfis_nome'))
    )
    op.create_table('permissoes',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissoes')),
    sa.UniqueConstraint('codigo', name=op.f('uq_permissoes_codigo'))
    )
    op.create_table('perfil_permissao',
    sa.Column('perfil_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('permissao_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], name=op.f('fk_perfil_permissao_perfil_id_perfis'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissoes.id'], name=op.f('fk_perfil_permissao_permissao_id_permissoes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('perfil_id', 'permissao_id', name=op.f('pk_perfil_permissao'))
    )
    op.create_table('setores',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('area_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_setores_area_id_areas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setores')),
    sa.UniqueConstraint('area_id', 'nome', name=op.f('uq_setores_area_id_nome'))
    )
    op.create_index(op.f('ix_setores_area_id'), 'setores', ['area_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('area_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('setor_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('ultimo_login_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_usuarios_area_id_areas')),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], name=op.f('fk_usuarios_perfil_id_perfis')),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], name=op.f('fk_usuarios_setor_id_setores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email'))
    )
    op.create_index(op.f('ix_usuarios_area_id'), 'usuarios', ['area_id'], unique=False)
    op.create_index(op.f('ix_usuarios_perfil_id'), 'usuarios', ['perfil_id'], unique=False)
    op.create_index(op.f('ix_usuarios_setor_id'), 'usuarios', ['setor_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('revogado_em', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_refresh_tokens_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_usuario_id'), 'refresh_tokens', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_usuario_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_usuarios_setor_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_perfil_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_area_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_setores_area_id'), table_name='setores')
    op.drop_table('setores')
    op.drop_table('perfil_permissao')
    op.drop_table('permissoes')
    op.drop_table('perfis')
    op.drop_table('areas')
    # ### end Alembic commands ###
