"""planos acoes historico

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-23 10:34:03.086540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('origens_plano',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_origens_plano')),
    sa.UniqueConstraint('nome', name=op.f('uq_origens_plano_nome'))
    )
    op.create_table('plano_sequencia',
    sa.Column('ano', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('ultimo_numero', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ano', name=op.f('pk_plano_sequencia'))
    )
    op.create_table('tipos_plano',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tipos_plano')),
    sa.UniqueConstraint('nome', name=op.f('uq_tipos_plano_nome'))
    )
    op.create_table('planos_de_acao',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('origem_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('area_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('setor_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('responsavel_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('criado_por_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('prazo_geral', sa.Date(), nullable=False),
    sa.Column('prioridade', sa.Enum('baixa', 'media', 'alta', 'critica', name='prioridade'), nullable=False),
    sa.Column('status', sa.Enum('rascunho', 'em_andamento', 'concluido', 'cancelado', name='status_plano'), nullable=False),
    sa.Column('descricao_problema', sa.Text(), nullable=True),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('causa', sa.Text(), nullable=True),
    sa.Column('evidencias', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_planos_de_acao_area_id_areas')),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], name=op.f('fk_planos_de_acao_criado_por_id_usuarios')),
    sa.ForeignKeyConstraint(['origem_id'], ['origens_plano.id'], name=op.f('fk_planos_de_acao_origem_id_origens_plano')),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], name=op.f('fk_planos_de_acao_responsavel_id_usuarios')),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], name=op.f('fk_planos_de_acao_setor_id_setores')),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_plano.id'], name=op.f('fk_planos_de_acao_tipo_id_tipos_plano')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planos_de_acao')),
    sa.UniqueConstraint('codigo', name=op.f('uq_planos_de_acao_codigo'))
    )
    op.create_index(op.f('ix_planos_de_acao_area_id'), 'planos_de_acao', ['area_id'], unique=False)
    op.create_index('ix_planos_de_acao_criado_em', 'planos_de_acao', ['criado_em'], unique=False)
    op.create_index(op.f('ix_planos_de_acao_criado_por_id'), 'planos_de_acao', ['criado_por_id'], unique=False)
    op.create_index(op.f('ix_planos_de_acao_origem_id'), 'planos_de_acao', ['origem_id'], unique=False)
    op.create_index(op.f('ix_planos_de_acao_prazo_geral'), 'planos_de_acao', ['prazo_geral'], unique=False)
    op.create_index(op.f('ix_planos_de_acao_responsavel_id'), 'planos_de_acao', ['responsavel_id'], unique=False)
    op.create_index(op.f('ix_planos_de_acao_setor_id'), 'planos_de_acao', ['setor_id'], unique=False)
    op.create_index(op.f('ix_planos_de_acao_status'), 'planos_de_acao', ['status'], unique=False)
    op.create_index(op.f('ix_planos_de_acao_tipo_id'), 'planos_de_acao', ['tipo_id'], unique=False)
    op.create_table('acoes',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('plano_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('responsavel_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('prazo', sa.Date(), nullable=False),
    sa.Column('prioridade', sa.Enum('baixa', 'media', 'alta', 'critica', name='prioridade'), nullable=False),
    sa.Column('status', sa.Enum('aguardando_aceite', 'aceita', 'em_andamento', 'bloqueada', 'concluida', 'recusada', 'cancelada', name='status_acao'), nullable=False),
    sa.Column('progresso', sa.SmallInteger(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('motivo_recusa', sa.String(length=500), nullable=True),
    sa.Column('motivo_bloqueio', sa.String(length=500), nullable=True),
    sa.Column('aceita_em', sa.DateTime(), nullable=True),
    sa.Column('concluida_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('progresso BETWEEN 0 AND 100', name=op.f('ck_acoes_progresso_0_100')),
    sa.ForeignKeyConstraint(['plano_id'], ['planos_de_acao.id'], name=op.f('fk_acoes_plano_id_planos_de_acao'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], name=op.f('fk_acoes_responsavel_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acoes'))
    )
    op.create_index('ix_acoes_criado_em', 'acoes', ['criado_em'], unique=False)
    op.create_index(op.f('ix_acoes_plano_id'), 'acoes', ['plano_id'], unique=False)
    op.create_index(op.f('ix_acoes_prazo'), 'acoes', ['prazo'], unique=False)
    op.create_index('ix_acoes_responsavel_status', 'acoes', ['responsavel_id', 'status'], unique=False)
    op.create_table('acao_historico',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('acao_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('usuario_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('evento', sa.Enum('criacao', 'alteracao', 'comentario', name='evento_historico'), nullable=False),
    sa.Column('campo_alterado', sa.String(length=50), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_novo', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acao_id'], ['acoes.id'], name=op.f('fk_acao_historico_acao_id_acoes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_acao_historico_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acao_historico'))
    )
    op.create_index('ix_acao_historico_acao_criado', 'acao_historico', ['acao_id', 'criado_em'], unique=False)
    op.create_index(op.f('ix_acao_historico_criado_em'), 'acao_historico', ['criado_em'], unique=False)
    op.create_index(op.f('ix_acao_historico_usuario_id'), 'acao_historico', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acao_historico_usuario_id'), table_name='acao_historico')
    op.drop_index(op.f('ix_acao_historico_criado_em'), table_name='acao_historico')
    op.drop_index('ix_acao_historico_acao_criado', table_name='acao_historico')
    op.drop_table('acao_historico')
    op.drop_index('ix_acoes_responsavel_status', table_name='acoes')
    op.drop_index(op.f('ix_acoes_prazo'), table_name='acoes')
    op.drop_index(op.f('ix_acoes_plano_id'), table_name='acoes')
    op.drop_index('ix_acoes_criado_em', table_name='acoes')
    op.drop_table('acoes')
    op.drop_index(op.f('ix_planos_de_acao_tipo_id'), table_name='planos_de_acao')
    op.drop_index(op.f('ix_planos_de_acao_status'), table_name='planos_de_acao')
    op.drop_index(op.f('ix_planos_de_acao_setor_id'), table_name='planos_de_acao')
    op.drop_index(op.f('ix_planos_de_acao_responsavel_id'), table_name='planos_de_acao')
    op.drop_index(op.f('ix_planos_de_acao_prazo_geral'), table_name='planos_de_acao')
    op.drop_index(op.f('ix_planos_de_acao_origem_id'), table_name='planos_de_acao')
    op.drop_index(op.f('ix_planos_de_acao_criado_por_id'), table_name='planos_de_acao')
    op.drop_index('ix_planos_de_acao_criado_em', table_name='planos_de_acao')
    op.drop_index(op.f('ix_planos_de_acao_area_id'), table_name='planos_de_acao')
    op.drop_table('planos_de_acao')
    op.drop_table('tipos_plano')
    op.drop_table('plano_sequencia')
    op.drop_table('origens_plano')
    # ### end Alembic commands ###
