"""arquivamento de planos

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-23 15:56:39.247350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planos_de_acao', sa.Column('arquivado_em', sa.DateTime(), nullable=True))
    op.add_column('planos_de_acao', sa.Column('arquivado_por_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True))
    op.create_index(op.f('ix_planos_de_acao_arquivado_em'), 'planos_de_acao', ['arquivado_em'], unique=False)
    op.create_foreign_key(op.f('fk_planos_de_acao_arquivado_por_id_usuarios'), 'planos_de_acao', 'usuarios', ['arquivado_por_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_planos_de_acao_arquivado_por_id_usuarios'), 'planos_de_acao', type_='foreignkey')
    op.drop_index(op.f('ix_planos_de_acao_arquivado_em'), table_name='planos_de_acao')
    op.drop_column('planos_de_acao', 'arquivado_por_id')
    op.drop_column('planos_de_acao', 'arquivado_em')
    # ### end Alembic commands ###
