"""descricao data_abertura anexos

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-23 16:22:39.073972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plano_anexos',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('plano_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('chave_armazenamento', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=False),
    sa.Column('enviado_por_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enviado_por_id'], ['usuarios.id'], name=op.f('fk_plano_anexos_enviado_por_id_usuarios')),
    sa.ForeignKeyConstraint(['plano_id'], ['planos_de_acao.id'], name=op.f('fk_plano_anexos_plano_id_planos_de_acao'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plano_anexos')),
    sa.UniqueConstraint('chave_armazenamento', name=op.f('uq_plano_anexos_chave_armazenamento'))
    )
    op.create_index(op.f('ix_plano_anexos_plano_id'), 'plano_anexos', ['plano_id'], unique=False)
    # Planos existentes: data de abertura = data de criação; depois a coluna passa a ser obrigatória.
    op.add_column('planos_de_acao', sa.Column('data_abertura', sa.Date(), nullable=True))
    op.execute("UPDATE planos_de_acao SET data_abertura = DATE(criado_em)")
    op.alter_column('planos_de_acao', 'data_abertura', existing_type=sa.Date(), nullable=False)
    op.add_column('planos_de_acao', sa.Column('descricao', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planos_de_acao', 'descricao')
    op.drop_column('planos_de_acao', 'data_abertura')
    op.drop_index(op.f('ix_plano_anexos_plano_id'), table_name='plano_anexos')
    op.drop_table('plano_anexos')
    # ### end Alembic commands ###
