"""historico do plano

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-23 16:44:10.144042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plano_historico',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('plano_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('usuario_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('evento', sa.Enum('criacao', 'alteracao', 'arquivamento', 'desarquivamento', name='evento_plano'), nullable=False),
    sa.Column('campo_alterado', sa.String(length=50), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_novo', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plano_id'], ['planos_de_acao.id'], name=op.f('fk_plano_historico_plano_id_planos_de_acao'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_plano_historico_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plano_historico'))
    )
    op.create_index('ix_plano_historico_plano_criado', 'plano_historico', ['plano_id', 'criado_em'], unique=False)
    # Planos existentes ganham o evento de criação (quem criou e quando), para a timeline começar completa.
    op.execute(
        "INSERT INTO plano_historico (plano_id, usuario_id, evento, campo_alterado, valor_novo, criado_em) "
        "SELECT id, criado_por_id, 'criacao', 'status', status, criado_em FROM planos_de_acao"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plano_historico_plano_criado', table_name='plano_historico')
    op.drop_table('plano_historico')
    # ### end Alembic commands ###
