"""solicitacoes notificacoes

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-23 17:23:09.990266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacoes',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('lida', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('lida_em', sa.DateTime(), nullable=True),
    sa.Column('referencia_tipo', sa.Enum('plano', 'acao', 'solicitacao', name='referencia_notificacao'), nullable=True),
    sa.Column('referencia_id', sa.BigInteger(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_notificacoes_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notificacoes'))
    )
    op.create_index('ix_notificacoes_usuario_lida_criado', 'notificacoes', ['usuario_id', 'lida', 'criado_em'], unique=False)
    op.create_table('acao_solicitacao_alteracao',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('acao_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('prazo_anterior', sa.Date(), nullable=False),
    sa.Column('novo_prazo_sugerido', sa.Date(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aceita', 'recusada', name='status_solicitacao'), nullable=False),
    sa.Column('feita_antes_do_aceite', sa.Boolean(), nullable=False),
    sa.Column('solicitado_por_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('respondido_por_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('resposta_justificativa', sa.Text(), nullable=True),
    sa.Column('respondido_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acao_id'], ['acoes.id'], name=op.f('fk_acao_solicitacao_alteracao_acao_id_acoes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['respondido_por_id'], ['usuarios.id'], name=op.f('fk_acao_solicitacao_alteracao_respondido_por_id_usuarios')),
    sa.ForeignKeyConstraint(['solicitado_por_id'], ['usuarios.id'], name=op.f('fk_acao_solicitacao_alteracao_solicitado_por_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acao_solicitacao_alteracao'))
    )
    op.create_index('ix_acao_solicitacao_acao_status', 'acao_solicitacao_alteracao', ['acao_id', 'status'], unique=False)
    op.add_column('acao_historico', sa.Column('detalhe', sa.Text(), nullable=True))
    # Novos eventos do histórico (o autogenerate não detecta mudança de valores de ENUM no MySQL).
    op.alter_column(
        'acao_historico', 'evento',
        existing_type=sa.Enum('criacao', 'alteracao', 'comentario', name='evento_historico'),
        type_=sa.Enum('criacao', 'alteracao', 'comentario', 'solicitacao', 'resposta_solicitacao', name='evento_historico'),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM acao_historico WHERE evento IN ('solicitacao', 'resposta_solicitacao')")
    op.alter_column(
        'acao_historico', 'evento',
        existing_type=sa.Enum('criacao', 'alteracao', 'comentario', 'solicitacao', 'resposta_solicitacao', name='evento_historico'),
        type_=sa.Enum('criacao', 'alteracao', 'comentario', name='evento_historico'),
        existing_nullable=False,
    )
    op.drop_column('acao_historico', 'detalhe')
    op.drop_index('ix_acao_solicitacao_acao_status', table_name='acao_solicitacao_alteracao')
    op.drop_table('acao_solicitacao_alteracao')
    op.drop_index('ix_notificacoes_usuario_lida_criado', table_name='notificacoes')
    op.drop_table('notificacoes')
    # ### end Alembic commands ###
