"""deduplicacao de notificacoes

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-24 09:26:46.775788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notificacoes', sa.Column('chave_deduplicacao', sa.String(length=191), nullable=True))
    op.create_unique_constraint(op.f('uq_notificacoes_chave_deduplicacao'), 'notificacoes', ['chave_deduplicacao'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_notificacoes_chave_deduplicacao'), 'notificacoes', type_='unique')
    op.drop_column('notificacoes', 'chave_deduplicacao')
    # ### end Alembic commands ###
