"""gamificacao

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-24 10:16:56.178670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamificacao_regras',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('gatilho', sa.Enum('plano_concluido', 'acao_no_prazo', 'acao_fora_do_prazo', name='gatilho_pontuacao'), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('aplica_a', sa.String(length=100), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('ordem', sa.SmallInteger(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gamificacao_regras')),
    sa.UniqueConstraint('gatilho', name=op.f('uq_gamificacao_regras_gatilho'))
    )
    op.create_table('gamificacao_lancamentos',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('regra_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('gatilho', sa.Enum('plano_concluido', 'acao_no_prazo', 'acao_fora_do_prazo', name='gatilho_pontuacao'), nullable=False),
    sa.Column('usuario_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.Column('referencia_tipo', sa.Enum('plano', 'acao', 'solicitacao', name='referencia_notificacao'), nullable=False),
    sa.Column('referencia_id', sa.BigInteger(), nullable=False),
    sa.Column('ocorrido_em', sa.DateTime(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regra_id'], ['gamificacao_regras.id'], name=op.f('fk_gamificacao_lancamentos_regra_id_gamificacao_regras')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_gamificacao_lancamentos_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gamificacao_lancamentos')),
    sa.UniqueConstraint('referencia_tipo', 'referencia_id', 'usuario_id', name='uq_gamificacao_lancamentos_referencia_usuario')
    )
    op.create_index('ix_gamificacao_lancamentos_ocorrido_usuario', 'gamificacao_lancamentos', ['ocorrido_em', 'usuario_id'], unique=False)
    op.create_index(op.f('ix_gamificacao_lancamentos_regra_id'), 'gamificacao_lancamentos', ['regra_id'], unique=False)
    op.create_index(op.f('ix_gamificacao_lancamentos_usuario_id'), 'gamificacao_lancamentos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###

    # Regras padrão (configuração do sistema; pontos e textos podem ser ajustados na tabela).
    regras = sa.table(
        'gamificacao_regras',
        sa.column('gatilho', sa.String), sa.column('nome', sa.String), sa.column('descricao', sa.String),
        sa.column('aplica_a', sa.String), sa.column('pontos', sa.Integer), sa.column('ordem', sa.SmallInteger),
    )
    op.bulk_insert(regras, [
        {'gatilho': 'plano_concluido', 'nome': 'Liderança Ativa', 'ordem': 1, 'pontos': 100,
         'descricao': 'Plano de ação 100% concluído.', 'aplica_a': 'Gestor (responsável pelo plano)'},
        {'gatilho': 'acao_no_prazo', 'nome': 'Disciplina Operacional', 'ordem': 2, 'pontos': 30,
         'descricao': 'Ação entregue dentro do prazo.', 'aplica_a': 'Executor (responsável pela ação)'},
        {'gatilho': 'acao_fora_do_prazo', 'nome': 'Resiliência e Entrega', 'ordem': 3, 'pontos': 10,
         'descricao': 'Ação entregue após o prazo.', 'aplica_a': 'Executor (responsável pela ação)'},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gamificacao_lancamentos_usuario_id'), table_name='gamificacao_lancamentos')
    op.drop_index(op.f('ix_gamificacao_lancamentos_regra_id'), table_name='gamificacao_lancamentos')
    op.drop_index('ix_gamificacao_lancamentos_ocorrido_usuario', table_name='gamificacao_lancamentos')
    op.drop_table('gamificacao_lancamentos')
    op.drop_table('gamificacao_regras')
    # ### end Alembic commands ###
