"""administracao

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-24 10:36:33.423342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.Column('atualizado_por_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], name=op.f('fk_configuracoes_atualizado_por_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('chave', name=op.f('pk_configuracoes'))
    )
    op.add_column('permissoes', sa.Column('acao', sa.String(length=20), server_default='outra', nullable=False))
    # ### end Alembic commands ###

    # Catálogo de permissões (retrato de app/core/permissoes.py nesta versão): insere as que faltam
    # e classifica todas na matriz módulo x ação.
    conn = op.get_bind()
    catalogo = [
        ('dashboard:ver', 'dashboard', 'visualizar', 'Visualizar o dashboard'),
        ('planos:ver', 'planos', 'visualizar', 'Visualizar planos de ação (da própria área e em que participa)'),
        ('planos:ver_todos', 'planos', 'outra', 'Visualizar planos de todas as áreas'),
        ('planos:criar', 'planos', 'criar', 'Criar planos de ação'),
        ('planos:editar', 'planos', 'editar', 'Editar e arquivar planos de qualquer autor'),
        ('acoes:ver_proprias', 'acoes', 'visualizar', 'Minhas Ações: ver e atualizar as próprias ações'),
        ('acoes:aprovar_prazo', 'acoes', 'aprovar', 'Responder solicitações de alteração de prazo'),
        ('equipes:ver', 'equipes', 'visualizar', 'Visualizar equipes'),
        ('calendario:ver', 'calendario', 'visualizar', 'Visualizar calendário'),
        ('indicadores:ver', 'indicadores', 'visualizar', 'Visualizar indicadores'),
        ('relatorios:ver', 'relatorios', 'visualizar', 'Visualizar e exportar relatórios'),
        ('notificacoes:ver', 'notificacoes', 'visualizar', 'Visualizar notificações'),
        ('gamificacao:ver', 'gamificacao', 'visualizar', 'Visualizar gamificação e eficiência'),
        ('admin:usuarios', 'administracao', 'outra', 'Gerenciar usuários'),
        ('admin:perfis', 'administracao', 'outra', 'Gerenciar perfis e permissões'),
        ('admin:areas', 'administracao', 'outra', 'Gerenciar áreas'),
        ('admin:setores', 'administracao', 'outra', 'Gerenciar setores'),
        ('admin:tipos_plano', 'administracao', 'outra', 'Gerenciar tipos de plano'),
        ('admin:configuracoes', 'administracao', 'outra', 'Gerenciar configurações'),
    ]
    for codigo, modulo, acao, descricao in catalogo:
        params = {'c': codigo, 'm': modulo, 'a': acao, 'd': descricao}
        existe = conn.execute(sa.text('SELECT id FROM permissoes WHERE codigo = :c'), params).scalar()
        if existe:
            conn.execute(sa.text('UPDATE permissoes SET modulo = :m, acao = :a, descricao = :d WHERE codigo = :c'), params)
        else:
            conn.execute(sa.text('INSERT INTO permissoes (codigo, modulo, acao, descricao) VALUES (:c, :m, :a, :d)'), params)

    # Administrador tem sempre todas as permissões; nenhum outro perfil tem as de administração.
    conn.execute(sa.text(
        "INSERT IGNORE INTO perfil_permissao (perfil_id, permissao_id) "
        "SELECT pf.id, pm.id FROM perfis pf CROSS JOIN permissoes pm WHERE pf.nome = 'Administrador'"
    ))
    conn.execute(sa.text(
        "DELETE pp FROM perfil_permissao pp JOIN perfis pf ON pf.id = pp.perfil_id "
        "JOIN permissoes pm ON pm.id = pp.permissao_id WHERE pm.modulo = 'administracao' AND pf.nome <> 'Administrador'"
    ))

    # Parâmetros globais, com os valores que antes estavam fixos no código.
    configuracoes = sa.table('configuracoes', sa.column('chave', sa.String), sa.column('valor', sa.String))
    op.bulk_insert(configuracoes, [
        {'chave': 'dias_alerta_vencimento_acao', 'valor': '3'},
        {'chave': 'dias_alerta_vencimento_plano', 'valor': '7'},
        {'chave': 'gamificacao_minimo_podio', 'valor': '3'},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissoes', 'acao')
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
